name: medal_table
description: A medal table showing ranking
version: 1.0.0
homepage: https://github.com/ozdemirberkay/
repository: https://github.com/ozdemirberkay/medal-table/
documentation: https://github.com/ozdemirberkay/medal-table/

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: